Repository travel-rx/fe-travel-rx, pull requests merged in 2019-12, with the labels that each got.

#27 Setup
  App.js
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/AppNavigator.js
  src/components/CreateAccount/CreateAccount.js
  src/components/CreateAccount/CreateAccount.test.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.test.js
  src/components/Header/Header.js
  src/components/Header/Header.test.js
  src/components/Home/Home.js
  src/components/Home/Home.test.js
  src/components/Login/Login.js
  src/components/Login/Login.test.js
  src/utils/apiCalls.js
  src/utils/apiCalls.test.js
Labels: design, fe-user-story, sprint 2

#28 Footer
  package-lock.json
  package.json
  src/components/About/About.js
  src/components/About/About.test.js
  src/components/AddMed/AddMed.js
  src/components/AddMed/AddMed.test.js
  src/components/AddPharmacy/AddParmacy.js
  src/components/AddPharmacy/AddPharmacy.test.js
  src/components/AddTrip/AddTrip.js
  src/components/AddTrip/AddTrip.test.js
  src/components/App/App.js
  src/components/AppNavigator.js
  src/components/FAQ/FAQ.js
  src/components/FAQ/FAQ.test.js
  src/components/Footer/Footer.js
  src/components/Header/Header.js
  src/components/Home/Home.js
  src/components/Login/Login.js
  src/components/MedicineCabinet/MedicineCabinet.js
  src/components/MedicineCabinet/MedicineCabinet.test.js
  src/components/Pharmacy/Pharmacy.js
  src/components/Pharmacy/Pharmacy.test.js
  src/components/Trips/Trips.js
  src/components/Trips/Trips.test.js
Labels: design, fe-user-story, sprint 2

#29 Component navigation
  .idea/TravelRx.iml
  .idea/codeStyles/Project.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  src/components/About/About.js
  src/components/AppNavigator.js
  src/components/CreateAccount/CreateAccount.js
  src/components/Footer/Footer.js
  src/components/Home/Home.js
  src/components/Login/Login.js
  src/components/MedicineCabinet/MedicineCabinet.js
  src/components/Trips/Trips.js
Labels: fe-user-story, sprint 2

#30 Structure and style components
  src/components/About/About.js
  src/components/AddMed/AddMed.js
  src/components/App/App.js
  src/components/AppNavigator.js
  src/components/CreateAccount/CreateAccount.js
  src/components/Home/Home.js
  src/components/Login/Login.js
  src/components/MedicineCabinet/MedicineCabinet.js
  src/components/Trips/Trips.js
Labels: fe-user-story, form, sprint 2
