Repository travel-rx/fe-travel-rx, pull requests merged in 2020-01, with the labels that each got.

#31 Format
  src/components/About/About.js
  src/components/AddMed/AddMed.js
  src/components/AddTrip/AddTrip.js
  src/components/AppNavigator.js
  src/components/CreateAccount/CreateAccount.js
  src/components/FAQ/FAQ.js
  src/components/MedicineCabinet/MedicineCabinet.js
  src/components/Trips/Trips.js
Labels: fe-user-story, form

#32 Redux
  package-lock.json
  package.json
  src/actions/actions.test.js
  src/actions/index.js
  src/components/App/App.js
  src/components/Home/Home.js
  src/components/MedicineCabinet/MedicineCabinet.js
  src/reducers/index.js
  src/reducers/meds.js
  src/reducers/trips.js
  src/reducers/user.js
  src/utils/apiCalls.js
Labels: fe-user-story

#33 Translation page
  src/components/AppNavigator.js
  src/components/EmergencyTranslations/EmergencyTranslations.js
  src/components/EmergencyTranslations/EmergencyTranslations.test.js
  src/components/EmergencyTranslations/data.js
  src/components/Footer/Footer.js
  src/components/Home/Home.js
  src/components/Trips/Trips.js
  src/reducers/user.js
Labels: fe-user-story

#34 Translation page
  src/components/AppNavigator.js
  src/components/EmergencyTranslations/EmergencyTranslations.js
  src/components/Footer/Footer.js
  src/components/Home/Home.js
  src/components/MedicineCabinet/MedicineCabinet.js
  src/utils/data.js
Labels: fe-user-story

#39 Med details
  src/components/About/About.js
  src/components/AddMed/AddMed.js
  src/components/AppNavigator.js
  src/components/EmergencyTranslations/EmergencyTranslations.js
  src/components/FAQ/FAQ.js
  src/components/Home/Home.js
  src/components/MedDetails/MedDetails.js
  src/components/MedDetails/MedDetails.test.js
  src/components/MedicineCabinet/MedicineCabinet.js
  src/utils/data.js
Labels: fe-user-story

#40 Styling and UI
  .idea/workspace.xml
  package-lock.json
  package.json
  src/components/AddMed/AddMed.js
  src/components/EmergencyTranslations/EmergencyTranslations.js
  src/components/Footer/Footer.js
  src/components/Home/Home.js
  src/components/MedDetails/MedDetails.js
  src/components/MedicineCabinet/MedicineCabinet.js
Labels: fe-user-story

#45 Delete
  src/components/AddMed/AddMed.js
  src/components/Home/Home.js
  src/components/Home/__snapshots__/Home.test.js.snap
  src/components/MedDetails/MedDetails.js
  src/components/MedicineCabinet/MedicineCabinet.js
  src/utils/apiCalls.js
Labels: Sprint 3, fe-user-story

#49 Delete three
  src/components/EmergencyTranslations/data.js
  src/components/MedDetails/MedDetails.js
  src/utils/apiCalls.js
Labels: Sprint 3, fe-user-story

#51 Api test
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/actions/index.html
  coverage/lcov-report/actions/index.js.html
  coverage/lcov-report/components/About/About.js.html
  coverage/lcov-report/components/About/index.html
  coverage/lcov-report/components/AddMed/AddMed.js.html
  coverage/lcov-report/components/AddMed/index.html
  coverage/lcov-report/components/EmergencyTranslations/EmergencyTranslations.js.html
  coverage/lcov-report/components/EmergencyTranslations/data.js.html
  coverage/lcov-report/components/EmergencyTranslations/index.html
  coverage/lcov-report/components/Footer/Footer.js.html
  coverage/lcov-report/components/Footer/index.html
  coverage/lcov-report/components/Home/Home.js.html
  coverage/lcov-report/components/Home/index.html
  coverage/lcov-report/components/MedDetails/MedDetails.js.html
  coverage/lcov-report/components/MedDetails/index.html
  coverage/lcov-report/components/MedicineCabinet/MedicineCabinet.js.html
  coverage/lcov-report/components/MedicineCabinet/index.html
  coverage/lcov-report/index.html
  coverage/lcov-report/utils/apiCalls.js.html
  coverage/lcov-report/utils/data.js.html
  coverage/lcov-report/utils/index.html
  coverage/lcov.info
  src/components/EmergencyTranslations/__snapshots__/EmergencyTranslations.test.js.snap
  src/components/Home/Home.js
  src/utils/apiCalls.test.js
Labels: Sprint 3, fe-user-story

#52 About
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/actions/index.html
  coverage/lcov-report/actions/index.js.html
  coverage/lcov-report/components/About/About.js.html
  coverage/lcov-report/components/About/index.html
  coverage/lcov-report/components/AddMed/AddMed.js.html
  coverage/lcov-report/components/AddMed/index.html
  coverage/lcov-report/components/EmergencyTranslations/EmergencyTranslations.js.html
  coverage/lcov-report/components/EmergencyTranslations/data.js.html
  coverage/lcov-report/components/EmergencyTranslations/index.html
  coverage/lcov-report/components/Footer/Footer.js.html
  coverage/lcov-report/components/Footer/index.html
  coverage/lcov-report/components/Home/Home.js.html
  coverage/lcov-report/components/Home/index.html
  coverage/lcov-report/components/MedDetails/MedDetails.js.html
  coverage/lcov-report/components/MedDetails/index.html
  coverage/lcov-report/components/MedicineCabinet/MedicineCabinet.js.html
  coverage/lcov-report/components/MedicineCabinet/index.html
  coverage/lcov-report/index.html
  coverage/lcov-report/utils/apiCalls.js.html
  coverage/lcov-report/utils/data.js.html
  coverage/lcov-report/utils/index.html
  coverage/lcov.info
  src/components/About/About.js
  src/components/EmergencyTranslations/__snapshots__/EmergencyTranslations.test.js.snap
  src/components/MedicineCabinet/__snapshots__/MedicineCabinet.test.js.snap
Labels: Sprint 3, design, documentation, enhancement, fe-user-story
